### ISSUE TITLE
[PW-2779] Adding a spinner/disabling button after click on Pay

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-prestashop#100]
**Is your feature request related to a problem? Please describe.**
If there's some network latency the user could spam Pay button, this will result in multiple transactions being made

**Describe the solution you'd like**
Adding a spinner and disabling the button after the first click to avoid such issues.

**Describe alternatives you've considered**
If a spinner is not possible at least disabling the button would make it.

Merchant requirement : DegriffStock

**Comment by AlexandrosMor** [comment]
Hello @YanP-Adyen,

Thank you for the suggestion. We created an internal ticket and we are going to pick it up soon.

regards,
Alexandros

**Comment by cyattilakiss** [comment]
Hi @YanP-Adyen 
Is it only happening in 1.6 right?
Thanks,
Attila
Adyen

**Comment by YanP-Adyen** [comment]
Hi @cyattilakiss 
Indeed the merchant is using Prestashop 1.6.1.18.

Regards.
