### ISSUE TITLE
[PW-2778] Displaying pm titles inside the UI block

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-prestashop#102]
**Is your feature request related to a problem? Please describe.**
As for now the title of the payment method is outside of the UI block. The merchant modified the CSS in order to achieve what he wants.

**Describe the solution you'd like**
It would be useful to have the option to display the PM titles inside (or outside) the UI block.

Merchant requirement : DegriffStock

**Comment by AlexandrosMor** [comment]
Hello @YanP-Adyen, 

Thank you for the suggestion. We created an internal ticket and we are going to pick it up soon.

regards,
Alexandros

**Comment by cyattilakiss** [comment]
Hi @YanP-Adyen ,

Could you please specify exactly what the UI block is where we should show the titles?
Are the titles of the default payment methods displayed there or are these displayed the same way as our payment methods in the plugin?

Thanks in advance,
Attila
Adyen

**Comment by YanP-Adyen** [comment]
Hi @cyattilakiss 
<img width="475" alt="Screen Shot 2020-10-05 at 8 47 44 AM" src="https://user-images.githubusercontent.com/68015043/95048068-7a0fcd00-06e7-11eb-8c4c-552fba3fb865.png">
It seems that the label "Régler par Carte bancaire" was outside of the grey area, the merchant had to modify a bit the CSS property to include it in. We can also see that the label is not aligned.

**Comment by cyattilakiss** [comment]
Hi @YanP-Adyen ,

We can fix the margin for the label but for the grey area the class `.js-payment-option-form` or `.row.adyen-payment` can be used.
In the next release we are going to remove the margin from the left side of the label since it's indeed unnecessary.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @YanP-Adyen ,

I am going to close this issue for now since we are going to introduce a bit different frontend structure that follows the default payment methods structure completely in 1.6 and 1.7 as well.

Best,
Attila
Adyen
