### ISSUE TITLE
Payment process goes slower than usually

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-prestashop#103]
**Describe the bug**
Seems that the payments process is now way slower than it was few days ago.
On our test instance : 
![Screen Shot 2020-07-24 at 4 50 35 PM](https://user-images.githubusercontent.com/68015043/88416484-98507700-cde0-11ea-9b95-d868dadc5ec8.png)

On the merchant (DegriffStock) side : 
![Screen Shot 2020-07-24 at 4 51 04 PM](https://user-images.githubusercontent.com/68015043/88416517-aa321a00-cde0-11ea-9fa6-823238ddca50.png)

As you can see it takes 4s on our test interface and almost 6s on the merchant website.
Exemple PSPReference : 
our prestashop : 853595602170812K
the merchant : 852595602080679D

On my own component test interface it only takes about 600ms.

**To Reproduce**
I used our test prestashop interface and made a payment with chrome's tool to monitor the network activity

**Expected behavior**
I don't have an example but transactions were quicker few days ago. In any case, 4s and 6s seems very slow to me.

**Screenshots**
See above.

**Comment by cyattilakiss** [comment]
Hi @YanP-Adyen 

You probably experience a slower response because the test Prestashop instance you are using is just for internal manual testing purposes only and when multiple people are using it it can be slower a bit.
I will close this ticket for now.

Best,
Attila
Adyen
