### ISSUE TITLE
2.1.4 adyenofficial.zip Missing Vendor Folder

### ISSUE THREAD

**Issue by CrafterLaughter** [Adyen/adyen-prestashop#104]
Just a heads up.  The 2.1.4 zip package you uploaded a few days past is missing the vendor folder.  The previous uploads appear to have it.  Also, there may have been something awry with 2.1.3 as when I tried to load that zip into Prestashop 1.7, Prestashop returns that it's not a valid module.  Not sure why.  Then I tried the 2.1.2 zip and it installed fine with Prestashop.

**Comment by cyattilakiss** [comment]
Hi @CrafterLaughter ,

Thank you for raising this issue. You are right the 2.1.4 is indeed missing the vendor folder.
I've released 2.1.5 with a patch and the missing vendor folder.
I will close this issue for now but please let us know if you still experience this issue with the latest version.

Best,
Attila
Adyen
