### ISSUE TITLE
[PW-2926] Plugin change 2 times the command status

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-prestashop#110]
**Describe the bug**
For unknown reasons, sometimes the shopper receives 2 email confirming its order.
With the merchant we saw that prestashop/the plugin was updating 2 times the order status to "payment accepted" within a 2/3 minutes gap.
This not very urgent nor blocking anything, but it leads the shopper thinking that he will pay 2 times.

![Untitled](https://user-images.githubusercontent.com/68015043/89662787-e2ebec00-d8d4-11ea-970f-6af9f43f6f84.png)

(No need to speak french ;))
at 16h34 the order is "payment accepted"
at 16h36 we receive the notification and the payment is set to accepted again.

The idea would be to understand why there is 2 status update.

The crontable is configued as follow

` * * * * * /usr/bin/curl -k "https://preprodurl/index.php?fc=module&controller=AdminAdyenOfficialPrestashopCron&token=..." `
` * * * * * /usr/bin/curl -k "https://liveurl/index.php?fc=module&controller=AdminAdyenOfficialPrestashopCron&token=..." `

**Comment by cyattilakiss** [comment]
Hi @YanP-Adyen ,

We try to reproduce this issue in the ticket: PW-2831
We will let you know if we could solve it or we need more info.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @YanP-Adyen ,

When processing the notifications we check if the order state is different than the paid state, which in this case is already the preparation after 1 minute the order has been paid. The reason for this is if the order is by any failure has been canceled (multiple payment trial with refused etc) an authorised notification could reopen the order and tag it correctly as paid.
AN internal ticket is created and we will investigate what statuses should be checked by the cron to avoid this.

Best,
Attila
Adyen
