### ISSUE TITLE
[PW-2497] Incompatibility with order-opc controller

### ISSUE THREAD

**Issue by ovega-webimpacto** [Adyen/adyen-prestashop#117]
It does not work when single page checkout is selected in PrestaShop versions 1.6.X.

**Steps to reproduce the behavior:**
1. Go to 'Preferences' -> 'Orders'
2. Click on 'Checkout in only page' in checkout type option
3. When trying to pay you can see that the Adyen payment options are not displayed.

**Additional info**
In adyenofficial.php file, in hookActionFrontControllerSetMedia not exist 'order-opc' controller in array. In registerAdyenAssets function not 'order-opc' section for management controller.

**Comment by acampos1916** [comment]
Hello @ovega-webimpacto,

Thanks for opening this issue. This indeed is a known problem and will be fixed in a future release.

Cheers,
Ángel
