### ISSUE TITLE
Oney3x4x : Adding installments view in checkout page

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-prestashop#123]
**Is your feature request related to a problem? Please describe.**
Oney is pushing for having an installment view in the checkout page. This will add more transparency with the shopper by giving him a clear view of what he'll pay.

**Describe the solution you'd like**
Here's a screenshot example given by Oney : 
![Untitled](https://user-images.githubusercontent.com/68015043/95303295-508ba880-0883-11eb-9e69-38e5c98e9c46.png)

**Additional context**
Note that this is not mandatory, however it would be a very nice value added feature.

**Comment by cyattilakiss** [comment]
Hi @YanP-Adyen ,

This should be implemented as well in the checkout component to benefit all merchants and all plugins not just prestashop.
I will close this issue for now.

Best,
Attila
Adyen
