### ISSUE TITLE
Attempted to call an undefined method named "setXApiKey"

### ISSUE THREAD

**Issue by dtesmanovic-webimpacto** [Adyen/adyen-prestashop#126]
Hello Support,

Recently I've installed the Adyen and configure on the test server and everything works well. After a while a migrated a site to another machine by transferring all FTP files and now sometimes I'm getting the error 500(on opening modules page-sometimes, on opening translations page-sometimes, when trying to use the search inside the Presta backoffice - always). Do you know what it could be?

-This is the full error report:
Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "setXApiKey" of class "Adyen\PrestaShop\service\Client"." at /web/mysite/modules/adyenofficial/service/Client.php line 63 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"setXApiKey\" of class \"Adyen\\PrestaShop\\service\\Client\". at /web/mysite/modules/adyenofficial/service/Client.php:63)"} []

- Prestashop version: 1.7.6.5
- PHP version: 7.2.3

Anything else, please let me know

Thank you

**Comment by msilvagarcia** [comment]
Hey @dtesmanovic-webimpacto !

It might be that the transfer missed a file in the `vendor` folder. Have you tried re-running a `composer install` or `composer update` in the new machine?

Kind regards,
Marcos
Adyen

**Comment by dtesmanovic-webimpacto** [comment]
Hi @msilvagarcia ,

Thanks for the tip. The composer update was done but no new results. I'm suspecting maybe in the nginx config of the server.

Thank you

**Comment by cyattilakiss** [comment]
Hi @dtesmanovic-webimpacto ,

Is this still an issue? In case you have figured out what was the problem could you please share it in a comment?

Thanks,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @dtesmanovic-webimpacto ,

I will close this issue for now but please feel free to reopen it if you still face this issue and we can assist with it.

Best,
Attila
Adyen
