### ISSUE TITLE
Vendor folder missing?

### ISSUE THREAD

**Issue by iLifehackNL** [Adyen/adyen-prestashop#145]
It is not possible for me to install the module, vendor folder should be included but there is none? Maybe I am not looking correctly. Seems only to be the case for the latest version.

**Comment by cyattilakiss** [comment]
Hi @iLifehackNL ,

Thank you for raising this issue. I just double checked it and indeed the vendor folder was not generated during the automated release process. I will regenerate the package and update it on the marketplace asap.
I will also update the package here on Github under the latest release assets.

The issue can also be solved running the `composer install` command but if you have no experience with composer it's better to wait for the zip file.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @iLifehackNL ,

The fix has been released in the 3.2.1 version.
I will close this issue for now but feel free to reopen it if you still face this issue.

Best,
Attila
Adyen
