### ISSUE TITLE
[PW-4033] Some terms cannot be translate

### ISSUE THREAD

**Issue by mehdi-ghezal** [Adyen/adyen-prestashop#155]
**Describe the bug**
Some terms cannot be translate in Prestashop backoffice because of the wrong use of $this->l()

Some examples here : 
 - https://github.com/Adyen/adyen-prestashop/blob/develop/adyenofficial.php#L1052
 - https://github.com/Adyen/adyen-prestashop/blob/develop/adyenofficial.php#L1096

**To Reproduce**
Try to translate Adyen module  in Prestashop backoffice ; "Pay by" isn't available.

**Expected behavior**
"Pay by" should be available in translation list.

**Comment by Morerice** [comment]
Hi @mehdi-ghezal 

Thank you for raising this issue.
This is a known issue on prestashop. We have recently started [fixing](https://github.com/Adyen/adyen-prestashop/pull/153/commits/0afb8f79b963ff56fc8112cded79b13e3379073f) some instances of these translations. Hence, we will be going trough all other instances (such as the ones you pointed out) soon.

Best regards,
Jeantwan
