### ISSUE TITLE
2 order lines for 1 payment

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-prestashop#187]
**Describe the bug**
Sometime 2 order lines are created instead of one.

**Screenshots**
As you can see there is 2 order lines "payment needs attention"
![image002](https://user-images.githubusercontent.com/68015043/114200649-b271bb80-9955-11eb-9a0e-cc5fa8ed857a.png)

Same here with status "Waiting FIA-NET validation" (???)
![image011](https://user-images.githubusercontent.com/68015043/114200676-b9003300-9955-11eb-8eb8-377070eec419.png)

More examples here
![image009](https://user-images.githubusercontent.com/68015043/114201074-1f855100-9956-11eb-8574-364270539d30.jpg)
![image010](https://user-images.githubusercontent.com/68015043/114201126-290eb900-9956-11eb-8578-4046a9db3155.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - 
**Additional context**
Logs line attached.
[adyen_notificationMarchApril.log](https://github.com/Adyen/adyen-prestashop/files/6286682/adyen_notificationMarchApril.log)
[infoMarchApril.log.zip](https://github.com/Adyen/adyen-prestashop/files/6286685/infoMarchApril.log.zip)

**Comment by Morerice** [comment]
Issue resolved by #176
