### ISSUE TITLE
[PW-4522] Few cents differences between prestashop order and Adyen payment

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-prestashop#188]
**Describe the bug**
Some orders are slightly different in terms of amount, for few cents

**Screenshots**
Examples : 4316154455083342
<img width="1442" alt="Screen Shot 2021-04-09 at 5 14 50 PM" src="https://user-images.githubusercontent.com/68015043/114202063-1fd21c00-9957-11eb-818b-78bdad76fd10.png">
+0.01 on Adyen's side

6519154092101150
<img width="1442" alt="Screen Shot 2021-04-09 at 5 15 50 PM" src="https://user-images.githubusercontent.com/68015043/114202212-41330800-9957-11eb-966d-26d78f902116.png">
-0.10 on Adyen's side

1316154044015975
<img width="1442" alt="Screen Shot 2021-04-09 at 5 16 23 PM" src="https://user-images.githubusercontent.com/68015043/114202300-5740c880-9957-11eb-8471-3a793c131f6a.png">
-0.01 on Adyen's side

**Additional context**
Logs attached (notification+info)
[adyen_notificationMarchApril.log](https://github.com/Adyen/adyen-prestashop/files/6286714/adyen_notificationMarchApril.log)

[infoMarchApril.log.zip](https://github.com/Adyen/adyen-prestashop/files/6286717/infoMarchApril.log.zip)

**Comment by Morerice** [comment]
Only a single merchant had this issue, which he was not able to re-produce and did not occur again in a span of 2 months
