### ISSUE TITLE
Prestashop module js error on checkout page

### ISSUE THREAD

**Issue by astrid2002** [Adyen/adyen-prestashop#194]
Hello

i have installed the adyen prestashop module version module 3.5.0

Prestashop verison 1.7.6.3 i am getting the following error on the front end part on the checkout page and of course i am not seeing the payment method.

https://bagprive.com/modules/adyenofficial/views/js/bundle.js
![Screen Shot 2021-05-10 at 20 07 49](https://user-images.githubusercontent.com/13542427/117839634-74392600-b28c-11eb-8ae3-fc3e5d01a2a5.png)

I don't have errors in the prestashop error log

**Comment by Morerice** [comment]
Hi @astrid2002 

I understand that you may not have any logs in your error file, but could you still provide us with your other logs? There should be information which should help us debug this issue.

Best regards,
Jean
Adyen

**Comment by astrid2002** [comment]
Hello this is a JS erro, server logs will be for php error or any conenxion error , i can give you the link of the website http://bagprive.com/

**Comment by Morerice** [comment]
Hi @astrid2002

I am aware that this is a JS error, but the error (should be an object but a string was provided) seems to be caused by a server-side call and hence, the requested logs should have more information regarding this.

Best regards,
Jean
Adyen

**Comment by Morerice** [comment]
Closing this ticket since there was no response after more than a month. Feel free to open another issue if problem occurs again.
