### ISSUE TITLE
Order created before payment is successful

### ISSUE THREAD

**Issue by llw-kl** [Adyen/adyen-prestashop#198]
Hi,

There is a problem with this module but I am not sure if it is a bug, design flaw or I have missed something. The issue occurs when a shopper clicks pay then cancels the transaction, decides to pay with a different method or inputs the wrong details. 

This is a particularly large problem when paying with 'Malaysia E-Banking'. Once a shopper selects pay, they are forwarded to an Adyen window where they can login to their bank. At this time, an order is created with an awaiting payment status. If the shopper cancels, chooses to use another payment method or inputs their details incorrectly, their cart will be empty when they return to the shop. There is no way for them to complete the sale. 

This issue occurs on Prestashop 1.6.1.21.

I believe the cart should only be converted to an order once the transaction is complete. If the transaction fails for any reason, the cart is still available so shoppers can try again 

I know another third party module uses this approach as the default mode. 

![Pending order](https://user-images.githubusercontent.com/41359537/119226415-914ae000-bb3b-11eb-8f63-a77b5f471b16.png)

Thanks so much for your consideration. 

Regards,

Luke

p.s. This report is related to issue #192

**Comment by Morerice** [comment]
Hi @llw-kl,

Thanks for opening this issue.
The logic which creates an order with an awaiting payment status was purposefully done so that while the payment is in this status, the stock is still reserved. This was also done so that in case for some reason the payment response was not received, but the payment went trough on our gateway, the payment would still be finalized when the payment notification is processed.

The issue where the cart is empty after a cancelled/failed payment is a bug. Could you please send the logs related to the [adyen plugin](https://docs.adyen.com/plugins/prestashop#downloading-the-logs) to support@adyen.com and link this github issue in the email?

In the meantime, we will start doing some investigation regarding this issue.

Best Regards,
Jean
Adyen

**Comment by llw-kl** [comment]
Hi @Morerice ,

Thank you so much for being so responsive and for all your help. 

I have been testing the new code. I am having a few issues with the notifications queuing up but I am not sure that this is related to the module. 

However, I can confirm that when I click cancel, the order is converted to 'cancelled' and the items return to the cart which is a lot better. 

I completely understand the route that you have taken by creating an order to reserving stock. I have checked the logs from my production server and found that approximately 13% of transactions failed and there are a vast number of cancelled. I worry that all my customers will have numerous cancelled orders in their accounts. 

I think the big issue for me is with online banking as an order is created before any bank details have been entered. 

I will continue to test and get back to you. 

Thanks again for all your help. 

Kind regards,

Luke

**Comment by llw-kl** [comment]
Hi @Morerice,

Thanks so much for your response and help. I have had an opportunity to test the module more thoroughly. The credit card processing flow is fantastic and causing no issues. I am having a bit of a headache with Malaysian E-Banking. There are two issues:

**Hour delay in converting rejected payments to cancelled orders**
 I have been creating test orders in Malaysian E-Banking which diverts me to the following page:

![3acquirer](https://user-images.githubusercontent.com/41359537/119777146-60322d00-bef8-11eb-9d50-443e247817ba.png)

If I select pending > authorised for 1 or 5 minutes, the order is converted to a 'payment accepted order' by Cron in the stipulated timeframe. If I select pending > refused, the order is cancelled but approximately one hour late. I have tested the webhook and I believe this is working correctly but it is reporting the unprocessed notification(s).

![6unprocessed](https://user-images.githubusercontent.com/41359537/119777840-4fce8200-bef9-11eb-9612-1dc83ce4c826.png)

I have checked the MYSQL table and the two orders (for 1370 and 1090) are refused but the 'done' field is still 0.   

![14 MYSQL-payment-accepted](https://user-images.githubusercontent.com/41359537/119782665-0aad4e80-beff-11eb-9966-000e12fc5110.png)

After one hour, the 'done' field becomes 1 and the timestamps are modified:

![16 MYSQL-payment-correct](https://user-images.githubusercontent.com/41359537/119779039-cc159500-befa-11eb-98f8-b2bd4306c106.png)

Initially, I thought I had messed up the Adyen configuration but I am sure that I have done it correctly. Also, the other transactions are working normally. 

**Orders created before any payment details entered for Malaysian B-Banking**
Again, I believe this will not affect the credit card payments as an order is only created once the correct card details have been verified. However, for E-Banking, the order is converted to an awaiting payment order once the pay button has been clicked:

![2ebanking](https://user-images.githubusercontent.com/41359537/119779946-d08e7d80-befb-11eb-9158-c0430f11da46.png)

If it is the same as my production system, the following page will be then be displayed:

![17-live-ebanking](https://user-images.githubusercontent.com/41359537/119780467-72ae6580-befc-11eb-95e5-41f9db1debdd.png)

If the user clicks previous, the order will be cancelled and the items returned to the cart. This will only result in some unwanted cancelled orders but be fully functional. However, if they click back on their browsers, or swipe right which is common on a mobile device, the order is created and the order will have to be cancelled manually. This is a particularly large problem for us as we are a secondhand bookshop and only have one copy of most products. Sadly, many of our customers use this payment method. 

I am so sorry to bother you again but any help would be greatly appreciated. 

Kind regards,

Luke

**Comment by Morerice** [comment]
Hi @llw-kl,

### Hour delay

This is part of our design, to ensure that notifications are executed in the correct order and avoid race conditions. This was done in https://github.com/Adyen/adyen-prestashop/pull/152. Specifically it was done to avoid this scenario:

* Error occurs during redirect which causes the refused notification to be sent
* Payment is successfully processed when the customer re-attempts the payment
* When notifications are processed, payment is moved from **waiting** to **cancelled** (first notification) and then from **cancelled** to **successful** (second notification).
* Hence the customer will receive one email saying that the order has been cancelled and another one saying that it was successful.

By delaying the cancelled notification for an hour, we ensure that if this scenario occurs, the payment will already be set to successful when we attempt to process the cancelled notification and therefore we can ignore this notification.
This delay is set [here](https://github.com/Adyen/adyen-prestashop/blob/e1a6892bdd4980c34a9982358c38eebbaec68f76/model/AdyenNotification.php#L235).

### Orders created before payment

Regarding this issue, we have the **OFFER_CLOSED** [notification](https://docs.adyen.com/development-resources/webhooks/understand-notifications#additional-configuration) which is specifically used when the customer abandons the session. To enable this notification, please contact our support team on support@adyen.com.

For future reference, if you have any issues such as these, related to how the plugin works please contact our support team. However, if you have more technical code-specific issues or a feature suggestion, you can open an issue here.

Best regards,
Jean
Adyen

**Comment by llw-kl** [comment]
@Morerice,

Sorry, I thought the delay was a bug. Thanks so much for all your help.

Regards,

Luke
