### ISSUE TITLE
Payment refuse creates an order automatically and clones to a new cart

### ISSUE THREAD

**Issue by ralegre-webimpacto** [Adyen/adyen-prestashop#230]
**Describe the bug**
Hello, this bug is kinda related to this issue #198

When you pay with Adyen and for example your card has 3D Secure step and you cancel it, the module creates an order with Payment error and duplicates your cart info to a new one, the idea is that now you finish the order with the correct info or other payment module.

The problem with this is that we have found multiple issues with other modules, we have already fixed 3 but we can't manage this constantly with each module we detect.

Modules that saves info into cart/order tables in sql will save on the Payment error order instead of the correct one.

Some examples would be Giftcards modules, Shipping carrier modules that uses relay points, or even google analytics info related to the order.

The giftcard will be linked to the first cart and order, same with the carrier relay point and the google analytics utm will be lost in the process.

**To Reproduce**
Go to final checkout step and choose adyen.
Use a card that has 3D Secure redirection.
Dont finish the order (cancel or use wrong data).
You will be redirected to an error message page with the option to return to checkout.
Internally a new order has been created and your cart data is cloned to a new one.

**Expected behavior**
There should be an option to don't create the order with Payment error so when you return to checkout you are still using the same cart and checkout session.

Prestashop version: 1.7.6.2

Module version: 3.3.0 with manual fix of #202

Thanks.

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x Prestashop integration has received a full overhaul. From October 1st 2023, we will offer a full featured, new integration that has been built from scratch. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
