### ISSUE TITLE
adyen change status order prestashop before payment is finisht

### ISSUE THREAD

**Issue by ikkiedikkie** [Adyen/adyen-prestashop#231]
Hello Attila,

sorry for my late response, but the issue still stands.
when the order is payed the total_paid_real is not filled in some cases.
this is wrong. this field is the value that how many is been payed

![image](https://user-images.githubusercontent.com/83693470/136844001-7b9eeb5d-b6de-4f97-b67a-a3aa14a3d141.png)

we run the latest version by our customer

gr Odin

_Originally posted by @ikkiedikkie in https://github.com/Adyen/adyen-prestashop/issues/192#issuecomment-940374277_

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x Prestashop integration has received a full overhaul. From October 1st 2023, we will offer a full featured, new integration that has been built from scratch. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
