### ISSUE TITLE
Adyen compatible onestepcheckout for Presatshop

### ISSUE THREAD

**Issue by HomeHeavenly** [Adyen/adyen-prestashop#233]
Hello,

I have integrated the Adyen module in PrestaShop 1.7. I also have an onestpecheckout module integrated with PrestaShop, which makes the Adyen module not show the payment methods.

I have contacted Adyen support, and they tell me that they only support the standard PrestaShop checkout and that is why I expose if the module can be improved.

I have seen that the module does not show the payment methods because when using the onestepcheckout it does not receive the checkoutSessionData value from the ps_cart table. This value will never be reported using the onestepcheckout mode, the value is filled in at the end of the purchase and not as in the standard PrestaShop check out method that is filled in when going from step 1 to 2.

I propose to change the condition of: if we are not in the payment step, described in line 1597 of the adyenofficial.php class, since when calling checkout->requireFecthPaymentMethods it will always return null in the case of onestepcheckout

Thanks in advance

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x Prestashop integration has received a full overhaul. From October 1st 2023, we will offer a full featured, new integration that has been built from scratch. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
