### ISSUE TITLE
Show payment method name for the order and not the generic 'Adyen'

### ISSUE THREAD

**Issue by drc0** [Adyen/adyen-prestashop#238]
**Describe the bug**
The payment method the user choosed (credit card, paypal, apple pay, google pay, etc) is not shown in the backend for each order nor the order confirmation email, instead a generic Adyen is shown. This is bad for two reasons, the user doesn't have a direct feedback on the used payment method, the admin doesn;t have a way to tell directly what payment method was used, and for example exporting from prestashop data for stat purpose.

**To Reproduce**
1. Perform an order
2. Go to admin / orders page
3. Adyen is shown instead of the payment method the user choosed

**Expected behavior**
A string representing the payment method is shown instead of the generic Adyen

**Additional context**
module 3.7.1

**Comment by drc0** [comment]
Any update?

**Comment by alexandrebrubeyonds** [comment]
Up, we need a correct name for payment method, it's important for admins.

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x Prestashop integration has received a full overhaul. From Oktober 1st 2023, we will offer a full featured, new integration that has been built from scratch. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
