### ISSUE TITLE
Move payment logs outside user messages

### ISSUE THREAD

**Issue by drc0** [Adyen/adyen-prestashop#239]
**Describe the bug**
Every log from adyen is shown in the order user messages,

![image](https://user-images.githubusercontent.com/5507633/151017185-e4ae160b-1085-4674-9e51-11fcb9349f87.png)

 would be better to move them inside a dedicated tab for the order, here is an example

![image](https://user-images.githubusercontent.com/5507633/151017390-46bdb345-28b0-49f1-aed3-f1134902cd1a.png)
![image](https://user-images.githubusercontent.com/5507633/151017484-28b1e4d7-4272-4745-a910-2b53632dc9b6.png)

**Additional context**
module 3.7.1

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x Prestashop integration has received a full overhaul. From Oktober 1st 2023, we will offer a full featured, new integration that has been built from scratch. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
