### ISSUE TITLE
Update Current_state in order

### ISSUE THREAD

**Issue by N0-buckets** [Adyen/adyen-prestashop#241]
Hello,

When i try to update the order status via API, i'm receiving the 500 error.
I'll do a PUT method to  "URL"/API/"order"
Where i'll get the order info first and alter the "current_state" node to the state that the client want. But the response is "Internal server error 500"
In the backoffice in the list you'll see that the state is diferent but if you open the order it isn't.

![image](https://user-images.githubusercontent.com/59091057/161739744-281332e9-7a9e-4385-ad15-4ffabcaa2fbb.png)

![image](https://user-images.githubusercontent.com/59091057/161739704-90affec0-3df7-4647-b339-78144c1e359e.png)

Can you please help?

Best regards

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x Prestashop integration has received a full overhaul. From Oktober 1st 2023, we will offer a full featured, new integration that has been built from scratch. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
