### ISSUE TITLE
Product customization is lost after payment is canceled/refused

### ISSUE THREAD

**Issue by cdue** [Adyen/adyen-prestashop#253]
**Describe the bug**
When buying a customized product (let's say a product on which you want a text to be engraved - you can add product customization fields on the Back-Office product page, in the options tab), if your payment is canceled or refused (failed 3D secure validation for example), the cart is duplicated, and the products that were in the previous cart are restored, but the product customizations are lost.
This is even worst if you're using the customization price impact feature because the price of the customization is also lost and the product price goes back to the default price (which may be 0 if the price totally depends on the customization).

**To Reproduce**
1. Create a customizable product (even with required customization fields) from the Back-Office
2. As a client (or guest), customize your product and add it to your cart
3. Go all the way down the payment funnel until you reach the payment step
4. Add valid card info (for example, the following credit card, which uses 3D secure: 4035 5014 2814 6300 - 03/30 - 737)
5. In the 3D secure modal, enter something wrong like 'ko' so that the 3D secure authentication fails
6. After you see the payment issue message, go to the cart
7. The product customization is lost

**Expected behavior**
The cart must be fully duplicated on a payment issue, including product customizations.

**Screenshots**
Cart before payment:
![image](https://user-images.githubusercontent.com/7940852/203591502-a34bb700-541a-45db-ba68-c22acd584211.png)

Cart after refused payment:
![image](https://user-images.githubusercontent.com/7940852/203592411-e1fd43c3-65e7-4aae-81fc-134fb0fdf6fe.png)
In this example, you can see that we're using the customization price impact feature, which leads to a product price of 0€ after the cart is cloned because the customization is lost. 

**Desktop:**
 - OS: macOS Ventura 13.0.1
 - Browser: Chrome
 - Prestashop Version: 1.7.7.8
 - Adyen module version: 4.0.0

**Comment by adyen-integrations-support** [comment]
Hello @cdue,

Thank you for reaching out. 

This is just a quick note to inform you that we received your request.

We will take this issue into consideration as soon as possible and keep you update.

Best regards.

**Comment by adyen-integrations-support** [comment]
Hello,

Please note that our team is still investigating this issue.
We will keep you posted about the progress.

If you have any further questions or concerns, please let us know.

Best regards.

**Comment by adyen-integrations-support** [comment]
Hello @cdue ,

Please note that our team managed to reproduce this issue in our local environment.
We also checked your fix and accepted it with a few slight changes.

This fix will be available in the next plugin release.
Of course, we will notify you when the new plugin is released on the marketplace and GitHub.

Best regards.

**Comment by cdue** [comment]
Perfect, thank you 👍
