### ISSUE TITLE
Unknown error when validating an order

### ISSUE THREAD

**Issue by Nesta78** [Adyen/adyen-prestashop#257]
Hi,

We have an issue with Prestashop module on a Prestahop 8.0 setup.

When processing order, an unknown error (red alert) is displayed as you can see on this video : https://www.awesomescreenshot.com/video/14138270?key=97885b9cd555fb14fdaa34b90395932d and the order is not validated (no confirmation page and so ... no emails sent). But we can see the new order in Prestashop Back-Office as if it was validated ...
Debug mode doesn’t help as it’s not displaying anything else.

- MacOS
- Chrome, Safari
- Prestashop 8.0.0

Thank you.

**Comment by adyen-integrations-support** [comment]
Hello @Nesta78 ,

Thank you for reaching out.

Please note that our team already started working on this issue.
Can you please confirm what Adyen plugin version are you using?

We will keep you posted.

Best regards.

**Comment by Nesta78** [comment]
Hi,

Version used is 4.0.2

**Comment by adyen-integrations-support** [comment]
@Nesta78 

Thank you,

We will investigate and get back to you as soon as possible.

Best regards.

**Comment by Nesta78** [comment]
Hello,
Is there any progress on the compatibility issue with Prestashop 8?
Thank you.

**Comment by adyen-integrations-support** [comment]
Hello @Nesta78 ,

Please note that our team analyzed the problem and found its root.
We are currently working on a solution and will notify you as soon as we fix it and test it.

If you have any further questions, please contact us.

Best regards.

**Comment by adyen-integrations-support** [comment]
Hello @Nesta78 ,

Please note that our team fixed and tested the issue and the new plugin version will be released next week.
We will notify you when the plugin is on the Marketplace and GitHub.

Best regards.

**Comment by Nesta78** [comment]
Thank you guys :)
