### ISSUE TITLE
Second Company or Second Module

### ISSUE THREAD

**Issue by OguzhanLevent** [Adyen/adyen-prestashop#260]
**Is your feature request related to a problem? Please describe.**

We have a Prestashop website where we sell our own products. Our European sales are done by a company based in Europe. We transfer to them and they send our products to our customers for a certain commission.

The company we cooperate with based in Europe prefers Adyen to receive payments. For this reason, we activated the module in our system about 1 year ago. We want to use Adyen because we observe it as a very healthy infrastructure.

First of all, I should state that "multishop" is not active. We have limited two different payment providers according to countries. We sell to countries outside Europe and our partner sells to European countries.

In this case, we contacted Adyen and created our account. We need to install a second module to distribute payments to countries. We have no information about how to do this. 

Ticket Id: #3826052 and #3867022 also have detailed information.

In this case we need information on how to install a second module.

Prestashop Version 1.7.8.8

best..

**Comment by adyen-integrations-support** [comment]
Hello @OguzhanLevent ,

Thank you very much for reaching out to us.
Our team already started investigating this matter.

We will keep you updated.

Best regards.

**Comment by adyen-integrations-support** [comment]
Hi @OguzhanLevent 

Please note that we already sent you a response with a detailed explanation in the ticket you created with Adyen support.

So please let us transfer our communication to the ticket that was created regarding this issue.

Thanks for understanding.

Best regards
