### ISSUE TITLE
New version available when already installed latest

### ISSUE THREAD

**Issue by Marco-online** [Adyen/adyen-prestashop#265]
After fresh install Prestashop and adyen latest plugin, plugins says newer version is available
 
![image](https://github.com/Adyen/adyen-prestashop/assets/11032488/05d40211-5e9f-41ac-9dd9-c6c01a7114f1)

update version is lower then installed 

![image](https://github.com/Adyen/adyen-prestashop/assets/11032488/699fd1cd-91a2-4195-81cf-034f15c8d138)

**Comment by DamjanLogeecom** [comment]
Hello @Marco-online,

Thank you for reaching out to us regarding this issue.

Our team is currently reviewing the issue you have raised and as soon as we have more information to provide, we will let you know.

Kind regards.

**Comment by DamjanLogeecom** [comment]
Hello @Marco-online ,

Please note that we have released a new version of the module in which the reported issue has been resolved.

You should update the plugin in your shop for the changes to take effect.

Thank you,

Kind regards.
