### ISSUE TITLE
Download button not working

### ISSUE THREAD

**Issue by Marco-online** [Adyen/adyen-prestashop#266]
button download new version links to  'https://logeecom.com/wp-content/uploads/2016/09/logo-white.png',

![image](https://github.com/Adyen/adyen-prestashop/assets/11032488/3fa3b07d-a350-4185-bd94-2cda91ccfd6b)

Change downloadVersionUrl to Git Repository ?!

**Comment by DamjanLogeecom** [comment]
Hello @Marco-online ,

Please note that we have released a new version of the module in which the reported issue has been resolved.

You should update the plugin in your shop for the changes to take effect.

Thank you,

Kind regards.
