### ISSUE TITLE
Need secure_key when you call validateOrder function

### ISSUE THREAD

**Issue by alexandrebrubeyonds** [Adyen/adyen-prestashop#269]
**Describe the bug**
The message "Warning: the secure key is empty, check your payment account before validation" is display in order confirmation message and mail alert commande.

The bug is from how you call the function validateOrder in modules/adyenofficial/controllers/PaymentController.php
You need to provide the secure_key in params.

**Comment by DamjanLogeecom** [comment]
Hello @alexandrebrubeyonds,

Thank you for reaching out to us,

Please note that our team will review your inquiry and as soon as we have some information, we will let you know.

Kind regards.

**Comment by logeecom** [comment]
Hello @alexandrebrubeyonds,

Please note that our team is still reviewing your inquiry.

As soon as we have more information to provide, we will let you know promptly.

Thank you,

Kind regards.

**Comment by logeecom** [comment]
Hello @alexandrebrubeyonds,

This is just a quick note to let you know that our team has fixed the reported issue.

These changes will be available in the next version of the Adyen/Prestashop plugin.

Thank you for your valuable suggestion.

If you have any further questions or concerns, please let us know.

Kind regards.

**Comment by alexandrebrubeyonds** [comment]
Great news, thanks :)
