### ISSUE TITLE
Refund not working on V5

### ISSUE THREAD

**Issue by alexandrebrubeyonds** [Adyen/adyen-prestashop#271]
When we make a refund in PrestaShop, nothing is sent to Adyen to automatically refund the payment.

It's a regression from previous module

**Comment by logeecom** [comment]
Hello @alexandrebrubeyonds,

Thank you for reaching out regarding this issue.

Could you please provide us with the additional information listed below?

**Steps to reproduce** - Information on how to reproduce a reported issue with detailed steps.

**Screenshots** - Screenshots that describe the issue.

**System version** - Prestashop system version.

**Plugin version** - Adyen plugin version installed to the integrated system.

After that, we will check the reported issue immediately and come back to you with feedback as soon as possible.

Thank you,

Kind regards.

**Comment by logeecom** [comment]
Hey @alexandrebrubeyonds 

Do you have any updates regarding this issue? Are you still experiencing the issue that you reported?

Kind regards.

**Comment by logeecom** [comment]
Dear @alexandrebrubeyonds,

As there has not been a response to this ticket for some time, we are closing it. 
If you have any further concerns or queries, please don't hesitate to get in touch with us again.

Best regards.
