### ISSUE TITLE
Adding order reference to transactions

### ISSUE THREAD

**Issue by kgrev** [Adyen/adyen-prestashop#275]
**Is your feature request related to a problem? Please describe.**
For a more accurate billing management, it would be nice to be able to tie an Adyen transaction to a specific Prestashop order instead of only using the cart ID, which does not appear on prestashop invoices.

**Describe the solution you'd like**
I've done some testings manipulating the prestashop module to send the order reference to Adyen when creating the transaction.
In this screenshot of Adyens transactions dashboard you can see I've tied the prestashop order reference to the Merchant Order Reference value which is not currently used by the module
![image](https://github.com/user-attachments/assets/e291c340-7779-47c3-8bf3-b8f3a3934983)

To do that I needed to create the order instance before sending the transaction request to Adyen on payment.php front controller on line 67.
![image](https://github.com/user-attachments/assets/e6212495-48e3-4008-9fe0-dd17e5be449f)

Then on the PaymentHttpRequest class I could attach the order reference to merchantOrderReference when building the requests body
![image](https://github.com/user-attachments/assets/ba01f811-a649-49da-80a9-1eaacf2f06c1)

As a result of these modifications, I can now do csv exports of my transactions on Adyen and see which order is attached to a specific transaction.

**Comment by adyen-integrations-support** [comment]
Hey @kgrev 

Thank you for reaching out!
Our team will check this and get back to you with more info.

Best regards.

**Comment by adyen-integrations-support** [comment]
Hi @kgrev,

Thank you for your suggestion regarding the new enhancement for our plugin. We always appreciate feedback and ideas. However, at this time, we do not have any plans to add new enhancements to the plugin, and we won't be implementing new features in the near future.

We truly value your input and thank you again for sharing your ideas with us.

Best regards
