### ISSUE TITLE
Checkout payment not use the good carrierId create difference in invoice and real payment 

### ISSUE THREAD

**Issue by Hydrog3n** [Adyen/adyen-prestashop#276]
**Describe the bug**
When paying the cart in the checkout page, the total of the order don't take the good carrierId
I saw in the version 5.2.0 a change here will get the default carrier id instead of the cart one that was done for the express checkout but create a bug on our side 

https://github.com/Adyen/adyen-prestashop/commit/ccaf609418cd0b03cb39583b6ef003aaf8a74ba4#diff-2ab6f53e1e407a0f7c2ddaf6d7d8f4551355d51ff172afeb5e5c4cee4b903dafR118

The total is compute with the wrong carrier Id here : https://github.com/Adyen/adyen-prestashop/blob/develop/src/controllers/PaymentController.php#L257-L259

**To Reproduce**
Having two differents carrier with different prices 
1. Add products to the cart
2. go to the checkout 
3. payed with adyen (Credit card)
4. In the Panel Adyen the amount is not the good amount 

**Expected behavior**

The total payed should be the good one

**Comment by adyen-integrations-support** [comment]
Hi,

Thank you for reaching out. We have successfully reproduced the issue on our end, and our development team is actively working on a resolution. We will update you as soon as we have more information.

Thank you for your patience.

Best regards

**Comment by adyen-integrations-support** [comment]
Hi @Hydrog3n ,

We're pleased to inform you that we've released a new version of the Adyen plugin (5.2.1) https://github.com/Adyen/adyen-prestashop/releases/tag/5.2.1 . This update includes a fix for the issue you experienced.

Please update to this latest version at your convenience, and let us know if there’s anything else we can assist you with.

Best regards

**Comment by Hydrog3n** [comment]
Thank you ! We will update the module soon
