### ISSUE TITLE
Critical performance issue and 500 errors due to cache clearing in getExpressCheckoutConfig function

### ISSUE THREAD

**Issue by alexandrebrubeyonds** [Adyen/adyen-prestashop#278]
Hello Adyen team,

I’ve encountered a critical performance issue with the Adyen PrestaShop module related to cache clearing. In the **getExpressCheckoutConfig** function, the following lines clear the cache each time express checkout is initialized:

Tools::clearAllCache();

This behavior results in substantial performance degradation and frequent 500 errors, especially on high-traffic stores. On a store with an average of 1000 visitors per day, the cache is cleared every second as visitors browse product pages or view the cart.

**Steps to Reproduce:**
	1.	Activate the Adyen module and configure express checkout.
	2.	Observe the impact on performance and frequent 500 errors as the system tries to access files being cleared.

**Expected Behavior:**
The cache should not be fully cleared every time express checkout is initialized, to avoid performance issues and 500 errors.

**Actual Behavior:**
Each initialization of express checkout clears the cache, leading to:
	•	Significant performance degradation.
	•	Frequent 500 errors, as parallel requests try to access files being deleted.

**Environment:**
	•	PrestaShop version: 1.7.8
	•	Adyen module version: 5.2.1

**Suggested Solution:**
A solution that minimizes or removes full cache clearing on each initialization would be ideal. Alternatively, clearing only the specific cache entries necessary for express checkout could be a viable fix.

We also need the possibility to desable express checkout on product page.

Thank you for your attention to this issue. Please let me know if further details are needed.

Best regards,
Alexandre BRU

**Comment by adyen-integrations-support** [comment]
Hello,

Thank you for reaching out. This is just a quick note to inform you that we received your ticket.

We will take this issue into consideration as soon as possible.

Best regards

**Comment by adyen-integrations-support** [comment]
Hey @alexandrebrubeyonds 

Please note that our team released a fix in this plugin version [5.2.3](https://github.com/Adyen/adyen-prestashop/releases/tag/5.2.3).

Best regards.
