### ISSUE TITLE
Payments not working on 5.2.3

### ISSUE THREAD

**Issue by alexandrebrubeyonds** [Adyen/adyen-prestashop#280]
On multiples orders, payment is captured and orders is not generated.
This error message is displayed for the customer, but payment is captured.

![Capture d’écran 2024-11-27 à 15 43 56](https://github.com/user-attachments/assets/23c461e7-b045-4965-ba51-a5fe41d75c80)
![image](https://github.com/user-attachments/assets/5c94f53e-e3d5-4993-bd27-3b3e2592f01a)

It's not working from 5.2.3

**Comment by adyen-integrations-support** [comment]
Hi @alexandrebrubeyonds ,

Thank you for bringing this to our attention. Our team is actively working on a fix to resolve this problem as soon as possible. We’ll keep you updated on the progress and let you know once the solution is ready.

Thank you for your patience and understanding.

Best regards

**Comment by adyen-integrations-support** [comment]
Hi @alexandrebrubeyonds ,

The new version of the plugin has been released (5.2.4) and it is available on GitHub.
https://github.com/Adyen/adyen-prestashop/releases/tag/5.2.4 


If you have any other questions let us know.

Best regards
