### ISSUE TITLE
Transaction details may contain an incorrect PSP reference and order amount in cases when 3DS authorization failed prior to successful authorization

### ISSUE THREAD

**Issue by dpuhach** [Adyen/adyen-prestashop#282]
**Describe the bug**
Transaction details may contain an incorrect PSP reference and order amount in cases when 3DS authorization failed prior to successful authorization.

**To Reproduce**
1. Try to pay by card with 3DSecure enabled.
2. Enter a wrong confirmation code once or more times.
3. Enter a correct confirmation code.
4. Check the newly created order in back-office.

**Expected behavior**
Transaction details provided by the Adyen module must contain the correct information regarding the successful transaction including correct "PSP reference" and "Order amount" (paid ammount).

**Screenshots**
<img width="1379" alt="image" src="https://github.com/user-attachments/assets/cb7a5083-b6c3-4059-9396-47c001a70043">
<img width="1338" alt="image" src="https://github.com/user-attachments/assets/92bd96a3-ec45-4009-b7ad-c60e8efcd4ad">

**Desktop (please complete the following information):**
 - (irrelevant)

**Smartphone (please complete the following information):**
 - (irrelevant)

**Additional context**
It seems that the failed authorization event is processed by the module after the successful authorization event and is written to the module transaction log in the same order. 
However, when displaying information in the upper part of the block with transaction details, information about the last authorization is displayed without taking into account whether it was successful or not.

**Comment by adyen-integrations-support** [comment]
Hello,

Thank you for reaching out. This is just a quick note to inform you that we received your ticket.

We will take this issue into consideration as soon as possible.

Best regards.
