### ISSUE TITLE
Failed opening required /modules/adyen/vendor/autoload.php' 

### ISSUE THREAD

**Issue by zobba** [Adyen/adyen-prestashop#48]
Bonjour,

Je voudrais installer ce module pour mon prestashop, après copier le dossier Adyen dans la répertoire modules, j'ai une page blanche avec ce message d'erreur :  
[PrestaShop] Fatal error in module file :/chemin de  mon prestashop/modules/adyen/adyen.php:
require(): Failed opening required '/chemin de  mon prestashop/modules/adyen/vendor/autoload.php' (include_path='/chemin de  mon prestashop/tools/htmlpurifier/standalone:.:/opt/remi/php70/root/usr/share/pear:/opt/remi/php70/root/usr/share/php:/usr/share/pear:/usr/share/php')

Je n'ai pas ce fichier : /modules/adyen/vendor/autoload.php ni la répertoire /modules/adyen/vendor.

Adyen: j'ai essayé la dernière branche dev et master, toujours le même message
PHP 7.0.9
nginx :1.15.6
Prestashop 1.6.1

Pourriez-vous me dire comment résoudre ce problème?

Je vous remercie.

Cordialement.

**Comment by zobba** [comment]
c'est ok, nous avons trouvé la solution, désolé pour déranger.

**Comment by G0urm** [comment]
Bonjour 
Dommage de ne pas avoir fourni la solution, car j'ai actuellement le même problème. :(

**Comment by acampos1916** [comment]
Bonjour @G0urm,

Did you follow the documentation to install the plugin? If you installed the plugin from the Github source I think you might be missing the `composer install --no-dev` step.

[Here are the installation instructions](https://docs.adyen.com/plugins/prestashop#install-the-plugin).

Cheers,
Ángel Campos
