### ISSUE TITLE
Cronjob causes 500 error

### ISSUE THREAD

**Issue by schenkelchen** [Adyen/adyen-prestashop#78]
I try to run the cronjob on my server with the following command:
`wget -q -O /dev/null "prestashop-XXX.cloudwaysapps.com/adminXXX/index.php?fc=module&controller=AdminAdyenPrestashopCron&token=XXX"`
It seems to me like it doesn't work so I also tried to run it by pasting the address into my browser. It results into an 500 error as shown in this screenshot:
https://raw.githubusercontent.com/schenkelchen/screenshots/master/adyen201_cronjob-test.PNG
Am I right that the cronjob should be running by pasting the address into my browser? Otherwise I don't know how to crosscheck if it's working.
My main issue with your module so far is that I can't perform refunds. Is that function related to cronjobs?

**Comment by cyattilakiss** [comment]
Hi @schenkelchen ,

Thank you for raising this issue. I was able to reproduce it, indeed it looks like we made a mistake when we performed the plugin name change from `adyen` to `adyenofficial` due to the marketplace submission.
We are going to fix it asap and release a fix.

Best,
Attila
Adyen

**Comment by schenkelchen** [comment]
Hi @cyattilakiss ,

thank you for checking on my issue so fast an releasing a new version of the module immediately.
I installed the new version 2.1.1 and found a good progress. I can access the cronjob address in my browser now without running into error 500.
But now I still get a negative feedback in the backoffice:

> The controller AdminAdyenOfficialPrestashopCron is missing or invalid.

https://raw.githubusercontent.com/schenkelchen/screenshots/master/adyen211_cronjob-test.PNG

Best,
Soeren

**Comment by cyattilakiss** [comment]
Hi @schenkelchen ,

Thanks for the response.
Let me check the new issue. 

Best,
Attila
Adyen
