### ISSUE TITLE
Notification test runs into 404 error

### ISSUE THREAD

**Issue by schenkelchen** [Adyen/adyen-prestashop#79]
Can you confirm that the following is the correct URL to be setup for 'Standard Notifications' in Adyen's 'Server communication settings'?
https://prestashop-XXX.cloudwaysapps.com/module/adyen/Notifications
Unfortunately I always get an error 404 as a result when performing the test in your 'Server communication settings' as shown in the screenshot:
https://raw.githubusercontent.com/schenkelchen/screenshots/master/adyen210_notifications-error.PNG

**Comment by acampos1916** [comment]
Hello @schenkelchen,

This would depend on the version of the plugin you're using, for the latest version the URL is `module/adyenofficial/Notifications`. Also, make sure to check if your store is set to use Friendly URLs.

Cheers,
Ángel

**Comment by schenkelchen** [comment]
Hello @acampos1916 ,

thank you very much for your fast response an the information about the URL change applying for the latest version of your module.
When I replace 'module/adyen/Notifications' with 'module/adyenofficial/Notifications' it works fine for me!
https://raw.githubusercontent.com/schenkelchen/screenshots/master/adyen210_notifications-working.PNG
It can be very helpful to others, if you write down this information on the respective Adyen Docs page section: https://docs.adyen.com/plugins/prestashop#set-up-notifications

Regards, Soeren

**Comment by acampos1916** [comment]
Hi @schenkelchen,

Indeed this is a recent change that has not been reflected on our docs, but this is being addressed now.

Thanks!
