### ISSUE TITLE
Cron job controller missing

### ISSUE THREAD

**Issue by schenkelchen** [Adyen/adyen-prestashop#83]
The issue about getting an error 500 when trying to run the cron job (#78) was solved well in #81!
With the modules newest version 2.1.1 appears a new error when running the cronjob in the browser's address line.
It appears the following feedback in the backoffice:

> The controller AdminAdyenOfficialPrestashopCron is missing or invalid.

https://raw.githubusercontent.com/schenkelchen/screenshots/master/adyen211_cronjob-test.PNG

**Comment by cyattilakiss** [comment]
Hi @schenkelchen ,

Could you please reinstall the plugin from the admin page?
It will reset for sure all the tabs, hooks, configurations and it will work as expected!
Please let me know if it helped!

Best,
Attila
Adyen

**Comment by schenkelchen** [comment]
Hi @cyattilakiss ,

thanks for your advice to reinstall the module.
Finally I did not only reinstall the module but delete it first of all. After deletion in backoffice I additionally deleted the complete directory `/public_html/modules/adyenofficial` in the file system.

After performing a new installation it's working now. Once I run the cron job in my browser address line I get a blank page. If I make a change to the token I get the message `Invalid token`. So it seems to me like a blank page means that everything works smoothly. (A suggestion from my side is to implement a short message to announce success in any further version of the module.)

Thank you once again for the good advice about how to solve my problem!

Best,
Soeren

**Comment by cyattilakiss** [comment]
Hi @schenkelchen ,

Happy to hear that it resolved the issue.
Thank you for the suggestion, indeed it makes sense to do so. We are going to pick this up into our backlog.

I will close this issue now.

Best,
Attila
Adyen
