### ISSUE TITLE
[PW-2671] Oney Bug

### ISSUE THREAD

**Issue by ClementLeboeuf** [Adyen/adyen-prestashop#89]
**Describe the bug**

The Oney payment method is active on the Adyen side, it appears on the payment page but the button is inactive.
![Oney](https://user-images.githubusercontent.com/68066683/87049782-ace81900-c1fd-11ea-98f1-f9ce6412ffb1.PNG)

Prestashop V1.6.1.18
Module Adyen V2.1.3

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cyattilakiss** [comment]
Hi @ClementLeboeuf ,

Thank you for raising this issue. We could verify that Oney doesn't work in the plugin for guest user checkouts but only for logged in users.
We have created a ticket: PW-2671 to keep track of this issue.
We are going to fix or propose a temporary solution asap.

Best,
Attila
Adyen
