### ISSUE TITLE
Bancontact Bug

### ISSUE THREAD

**Issue by ClementLeboeuf** [Adyen/adyen-prestashop#90]
**Describe the bug**

The Bancontact payment method is active on Adyen and on Prestashop.
The Adyen Test Card was refused during the tests on the test account.

Example of 
![bancontact](https://user-images.githubusercontent.com/68066683/87050714-ee2cf880-c1fe-11ea-94c7-eda371a9ab10.PNG)
transaction reference : 881594135198525J

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by YanP-Adyen** [comment]
Internal : the response to the bcmc payment is 
`{
   "status" : 422,
   "errorCode" : "101",
   "message" : "Invalid card number",
   "errorType" : "validation",
   "pspReference" : "881594135198525J"
}`

Something strange : in the request I don't see any card details...
` "card" : {
      "holderName" : "Checkout Shopper PlaceHolder"
   }`

**Comment by cyattilakiss** [comment]
Hi @ClementLeboeuf , @YanP-Adyen 

Which test card was used exactly during the test?
https://docs.adyen.com/development-resources/test-cards/test-card-numbers#bancontact-bcmc

Thank you in advance,
Attila
Adyen

**Comment by YanP-Adyen** [comment]
Hi @cyattilakiss we tried with both of them with the same result.

6703 4444 4444 4449 | 03/2030
6703 0000 0000 0000 003 | 03/2030

**Comment by cyattilakiss** [comment]
Hi @YanP-Adyen ,

I've just created 2 successful test payments on a default prestashop 1.7 setup with the plugin with the test numbers mentioned above.
Could you please create a ticket on our support page and provide us the log files for the failed transaction?
Also just in case if you can provide us a staging site where we can reproduce the issue that could help us find the issue.
I will close this issue for now.

Best,
Attila
Adyen
